sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  aliyun:
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      bucket-name: yzf-waimai
  wechat:
    appid: wx7e8e706d6932663f
    secret: 46d8d6a0a74c3064d78dd14b0b7d79df
